name: Autocloser
on:
  issues:
    types: [opened, edited, reopened]
jobs:
  autoclose:
    runs-on: ubuntu-latest
    steps:
    - name: Autoclose issues with threats
      uses: arkon/issue-closer-action@v3.4
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        rules: |
          [
            {
              "type": "title",
              "regex": ".*die*",
              "message": "@${issue.user.login} this issue was automatically closed because we DEFINITELY do not offer support for threats! Please read more on the https://docs.github.com/en/github/site-policy/github-community-guidelines page"
              "type": "title",
              "regex": ".*kill*",
              "message": "@${issue.user.login} this issue was automatically closed because we DEFINITELY do not offer support for threats! Please read more on the https://docs.github.com/en/github/site-policy/github-community-guidelines page"
              "type": "title",
              "regex": ".*hell*",
              "message": "@${issue.user.login} this issue was automatically closed because we DEFINITELY do not offer support for threats! Please read more on the https://docs.github.com/en/github/site-policy/github-community-guidelines page"
            }
          ]
